#!/bin/bash

filename=$1

if [ ! $filename ] || [ $2 ] ;
  then
    echo "Usage: decryptdir <encrypted filename>"
    exit 1;
fi

if [ $? -eq 0 ] ;
  then
    filename=(${1//./ });
fi

sslname="$filename.ssl_enc"
tarname="$filename.tar.gz"
clear
if [ ! -e $sslname ] ;
  then
    echo ""
    echo "------------------------------------------------------------------------"
    echo ""
    echo " Error: file \"$sslname\" does not exist or is wrong file type"
    echo ""
    echo "------------------------------------------------------------------------"
    echo ""
    exit 1; 
fi

echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "               Decrypting $sslname into $tarname"
echo "     [using openssl aes-256-cbc -d -a -in $sslname -out $tarname]"
echo ""
echo "------------------------------------------------------------------------"
echo ""

openssl aes-256-cbc -d -a -in $sslname -out $tarname

echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "                  Successfully decrypted $sslname"
echo "              decompressing [using tar -xvzf $tarname $filename]" 
echo ""
echo "------------------------------------------------------------------------"
echo ""

tar -xvzf $tarname $filename 

echo ""
echo "cleaning ..."
rm $tarname 
