#!/bin/bash

filename=$1

echo $filename
echo $2

if [ ! $filename ] || [ $2 ] ;
  then
    echo "Usage: decryptdir <encrypted filename>"
    exit 1;
fi

echo "$1" | grep -q ".\+\.ssl_enc"
if [ $? -eq 0 ] ;
  then
    filename=(${1//./ });
fi

clear
if [ ! -e $filename.ssl_enc ] ;
  then
    echo ""
    echo "------------------------------------------------------------------------"
    echo ""
    echo $"	     Error: file \"$filename.ssl_enc\" does not exist or is wrong file type"
    echo ""
    echo "------------------------------------------------------------------------"
    echo ""
    exit 1; 
fi
echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "               Decrypting $filename.ssl_enc into $filename.tar.gz"
echo "     [using openssl aes-256-cbc -d -a -in $filename.ssl_enc -out $filename.tar.gz]"
echo ""
echo "------------------------------------------------------------------------"
echo ""

openssl aes-256-cbc -d -a -in $filename.ssl_enc -out $filename.tar.gz

echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "                  Successfully decrypted $filename.ssl_enc"
echo "              decompressing [using tar -xvzf $filename.tar.gz $filename]" 
echo ""
echo "------------------------------------------------------------------------"
echo ""

tar -xvzf $filename.tar.gz $filename 

echo ""
echo "cleaning ..."
rm $filename.tar.gz
