#!/bin/bash

if [ $# -ne 1 ];
  then
    echo "Usage: encryptdir <dir-name to encrypt>"
    exit 1;
fi

if [ ! -d $1 ] ;
  then
    echo ""
    echo "------------------------------------------------------------------------"
    echo ""
    echo "	        Error: Directory \"$1\" does not exist"
    echo ""
    echo "------------------------------------------------------------------------"
    echo ""
    exit 1; 
fi

lastChar="${1##${1%%?}}"
if [ "$lastChar" = "/" ] ;
  then
    echo "Please do not include \"/\" at the end of folder name"
    exit 1;
fi

echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "    Compressing $1 to $1.tar.gz [using: tar -cvzf $1.tar.gz $1]"
echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "Compressing..."
echo ""

set +e
tarname="$1.tar.gz"
tar -cvzf $tarname $1

if [ $? -eq 2 ]; 
  then
    echo "tar has encountered an error"
    exit 1;
fi
set -e

sslname="$1.ssl_enc"
echo ""
echo "------------------------------------------------------------------------"
echo ""
echo "                  Encrypting $tarname to $sslname"
echo "   [using: openssl aes-256-cbc -a -salt -in $tarname -out $sslname"
echo ""
echo "------------------------------------------------------------------------"
echo ""

openssl aes-256-cbc -a -salt -in $tarname -out $sslname
echo ""
echo "Cleaning..."
rm $tarname 
